<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <title>Sucos Juices - a melhor opção!</title>
        <link rel="stylesheet" type="text/css" href="./web-files/reset.css" />
        <link rel="stylesheet" type="text/css" href="./web-files/style.css" />
        <script type="text/javascript" src="./web-files/scripts/jquery.js"></script>
        <script type="text/javascript" src="./web-files/scripts/selectivizr.js"></script>
        <link rel="shortcut icon" href="./web-files/favicon.ico" />
        <link rel="icon" href="./web-files/favicon.ico" />
    </head>

    <body>
        <div id="geral">
            <div id="topo">
                <h1 id="logo">
                    <a href="./index">Sucos Juices</a>
                </h1><!-- Logo -->

                <ul id="menu">
                    <li><a href="./index">Home</a></li>
                    <li><a href="./quemsomos">Quem somos</a></li>
                    <li class="current"><a href="./servicos">Serviços</a></li>
                    <li><a href="./faleconosco">Fale conosco</a></li>
                </ul><!-- Menu -->
            </div><!-- Topo -->

            <div id="corpo">
                <div id="esq">
                    <div id="paginas">
                        <h1>Serviços</h1>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            Fusce auctor tristique magna eu dapibus. Integer sed magna
                            quam, sed aliquam lectus. Proin massa tortor, blandit in
                            mattis sit amet, interdum nec nibh. Maecenas pellentesque
                            lorem vitae risus vestibulum malesuada. Phasellus ante augue,
                            molestie in facilisis sed, dictum in orci. Pellentesque
                            tincidunt nibh nec diam ultricies eget auctor magna luctus.
                            Aenean dictum porta diam, nec fermentum justo ornare in.
                            Pellentesque at elit eu orci suscipit condimentum. Quisque
                            non massa in justo tristique euismod eget ac purus. Suspendisse
                            .
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            Fusce auctor tristique magna eu dapibus. Integer sed magna
                            quam, sed aliquam lectus. Proin massa tortor, blandit in
                            mattis sit amet, interdum nec nibh. Maecenas pellentesque
                            lorem vitae risus vestibulum malesuada. Phasellus ante augue,
                            molestie in facilisis sed, dictum in orci. Pellentesque
                            tincidunt nibh nec diam ultricies eget auctor magna luctus.
                            Aenean dictum porta diam, nec fermentum justo ornare in.
                            Pellentesque at elit eu orci suscipit condimentum. Quisque
                            non massa in justo tristique euismod eget ac purus. Suspendisse
                            .
                        </p>
                    </div><!-- Paginas -->
                </div><!-- Esquerda -->

                <div id="dir">
                    <div id="socials">
                        <div class="twitter">
                            <small>3498</small>
                            <p>Followers</p>
                        </div><!-- Twitter -->
                        
                        <div class="rss">
                            <small>1549</small>
                            <p>Acessos</p>
                        </div><!-- Rss -->

                        <div class="clear"></div>
                    </div><!-- Socials -->

                    <div id="receitas">
                        <h3>Receitas:</h3>
                        <ul>
                            <?php foreach ($view_receitas_lista as $receitas_lista): ?>
                                <li><a href="./receitas/artigo/id/<?php echo $receitas_lista['id']; ?>"><?php echo $receitas_lista['titulo']; ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </div><!-- Receitas -->
                </div><!-- Direita -->

                <div class="clear espaco-rodape"></div>
            </div><!-- Corpo -->

            <div id="rodape">
                <ul id="nav">
                    <li><a href="/index">Home</a></li>
                    <li><a href="/quemsomos">Quem somos</a></li>
                    <li><a href="/servicos">Serviços</a></li>
                    <li><a href="/faleconosco">Fale conosco</a></li>
                </ul><!-- Nav -->

                <p class="copyright">2011 - Sucos Juices - Todos os direitos reservados</p>
            </div><!-- Rodape -->
        </div><!-- Geral -->
    </body>
</html>